# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tpokalch <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/23 18:33:25 by tpokalch          #+#    #+#              #
#    Updated: 2018/11/10 21:56:45 by tpokalch         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: 
	 gcc -Werror -Wextra -Wall ft_display_file.c -o ft_display_file

clean:
	 rm -rf *.o

fclean: clean
	 rm -rf ft_display_file
	
re: fclean all
